const fs = require('fs');
const path = require('path');

const indexPath = path.join(__dirname, '..', 'index.html');
if (!fs.existsSync(indexPath)) {
  console.error('index.html not found at project root');
  process.exit(1);
}

const contents = fs.readFileSync(indexPath, 'utf8');
if (!contents.includes('Welcome to the website generated by my demo repository')) {
  console.error('Expected headline not found in index.html');
  process.exit(1);
}

console.log('Smoke check passed: index.html contains the expected headline.');
